/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sig.view;

/**
 *
 * @author Conexão Web
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        lblOperador = new javax.swing.JLabel();
        operador = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCoprRight = new javax.swing.JLabel();
        lblDevelopment = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuServicos = new javax.swing.JMenu();
        menuServico = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        menuCliente = new javax.swing.JMenuItem();
        menuFuncionarios = new javax.swing.JMenu();
        menuFuncionario = new javax.swing.JMenuItem();
        menuFornecedores = new javax.swing.JMenu();
        menuFornecedor = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        aCaixa = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuConfiguracao = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIG-Dashboard");
        setMinimumSize(new java.awt.Dimension(850, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        lblOperador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOperador.setText("Operador:");

        operador.setBackground(new java.awt.Color(240, 3, 55));
        operador.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("© Copy Right 2022");

        lblCoprRight.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCoprRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCoprRight.setText("© Copy Right 2022");

        lblDevelopment.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDevelopment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDevelopment.setText("Desenvolvido pela: Conexão Web");

        jMenuBar1.setFocusCycleRoot(true);

        menuServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sig/icones/prod.png"))); // NOI18N
        menuServicos.setText("Serviços");
        menuServicos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServicosActionPerformed(evt);
            }
        });

        menuServico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sig/icones/gr.png"))); // NOI18N
        menuServico.setText("Gerir Serviços");
        menuServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServicoActionPerformed(evt);
            }
        });
        menuServicos.add(menuServico);

        jMenuBar1.add(menuServicos);

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sig/icones/user1.png"))); // NOI18N
        menuClientes.setText("Clientes");
        menuClientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        menuCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sig/icones/gr.png"))); // NOI18N
        menuCliente.setText("Gerir Clientes");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        menuClientes.add(menuCliente);

        jMenuBar1.add(menuClientes);

        menuFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sig/icones/users.png"))); // NOI18N
        menuFuncionarios.setText("Funcionários");
        menuFuncionarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        menuFuncionario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sig/icones/gr.png"))); // NOI18N
        menuFuncionario.setText("Gerir Funcionários");
        menuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionarioActionPerformed(evt);
            }
        });
        menuFuncionarios.add(menuFuncionario);

        jMenuBar1.add(menuFuncionarios);

        menuFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sig/icones/func1.png"))); // NOI18N
        menuFornecedores.setText("Fornecedores");
        menuFornecedores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        menuFornecedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sig/icones/gr.png"))); // NOI18N
        menuFornecedor.setText("Gerir Fornecedores");
        menuFornecedores.add(menuFornecedor);

        jMenuBar1.add(menuFornecedores);

        menuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sig/icones/cart1.png"))); // NOI18N
        menuVendas.setText("Vendas");
        menuVendas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendasActionPerformed(evt);
            }
        });

        aCaixa.setText("Abrir caixa");
        aCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aCaixaActionPerformed(evt);
            }
        });
        menuVendas.add(aCaixa);

        jMenuItem2.setText("Histórico de vendas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuVendas.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        menuVendas.add(jMenuItem3);

        jMenuBar1.add(menuVendas);

        menuConfiguracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sig/icones/fer.png"))); // NOI18N
        menuConfiguracao.setText("Configurações");
        menuConfiguracao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jMenuBar1.add(menuConfiguracao);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sig/icones/sair.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(operador, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblOperador)
                .addGap(266, 266, 266)
                .addComponent(lblCoprRight, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblDevelopment, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addComponent(desktop)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(378, 378, 378)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(379, 379, 379)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCoprRight)
                        .addComponent(lblDevelopment))
                    .addComponent(operador, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOperador))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(197, 197, 197)
                    .addComponent(jLabel8)
                    .addContainerGap(246, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setVisible(true);
    }//GEN-LAST:event_formWindowActivated

    private void menuServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServicosActionPerformed
            // TODO add your handling code here:
            ClienteView sv = new ClienteView();
            sv.setVisible(true);
            desktop.add(sv);
            
//            sv.show();
            
    }//GEN-LAST:event_menuServicosActionPerformed

    private void menuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendasActionPerformed
        // TODO add your handling code here:
//         ServicosView sv = new ServicosView();
//            
//            desktop.add(sv);
//            desktop.show();
//            sv.setVisible(true);
    }//GEN-LAST:event_menuVendasActionPerformed

    private void aCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aCaixaActionPerformed
        // TODO add your handling code here:
        
            
            
    }//GEN-LAST:event_aCaixaActionPerformed

    private void menuServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServicoActionPerformed
        // TODO add your handling code here:
        ServicosView sv = new ServicosView();
        desktop.add(sv);
//sv.show();
        sv.setVisible(true);
    }//GEN-LAST:event_menuServicoActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        // TODO add your handling code here:
        ClientesView cv = new ClientesView();
        desktop.add(cv);
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionarioActionPerformed
        // TODO add your handling code here:
        FuncionariosView fv = new FuncionariosView();
        desktop.add(fv);
    }//GEN-LAST:event_menuFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aCaixa;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblCoprRight;
    private javax.swing.JLabel lblDevelopment;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuConfiguracao;
    private javax.swing.JMenuItem menuFornecedor;
    private javax.swing.JMenu menuFornecedores;
    private javax.swing.JMenuItem menuFuncionario;
    private javax.swing.JMenu menuFuncionarios;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem menuServico;
    private javax.swing.JMenu menuServicos;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JLabel operador;
    // End of variables declaration//GEN-END:variables
}
