/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sig.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import sig.controller.*;

/**
 *
 * @author Conexão Web
 */
public class FuncionariosView extends javax.swing.JInternalFrame {

    FuncionarioController fc;

    /**
     * Creates new form FuncionariosView
     */
    public FuncionariosView() {
        initComponents();
        fc = new FuncionarioController();
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public JTextArea getTxtEndereco() {
        return txtEndereco;
    }

    public void setTxtEndereco(JTextArea txtEndereco) {
        this.txtEndereco = txtEndereco;
    }

    public JTextField getTxtMunicipio() {
        return txtMunicipio;
    }

    public void setTxtMunicipio(JTextField txtMunicipio) {
        this.txtMunicipio = txtMunicipio;
    }

    public JTextField getTxtNif() {
        return txtNif;
    }

    public void setTxtNif(JTextField txtNif) {
        this.txtNif = txtNif;
    }

    public JTextField getTxtNome() {
        return txtNome;
    }

    public void setTxtNome(JTextField txtNome) {
        this.txtNome = txtNome;
    }

    public JComboBox getCmbxPais() {
        return cmbxPais;
    }

    public void setCmbxPais(JComboBox cmbxPais) {
        this.cmbxPais = cmbxPais;
    }

    public JPasswordField getTxtSenha() {
        return txtSenha;
    }

    public void setTxtSenha(JPasswordField txtSenha) {
        this.txtSenha = txtSenha;
    }

    public JTextField getTxtTelefone1() {
        return txtTelefone1;
    }

    public void setTxtTelefone1(JTextField txtTelefone1) {
        this.txtTelefone1 = txtTelefone1;
    }

    public JTextField getTxtTelefone2() {
        return txtTelefone2;
    }

    public void setTxtTelefone2(JTextField txtTelefone2) {
        this.txtTelefone2 = txtTelefone2;
    }

    public JComboBox<String> getCmbxGenero() {
        return cmbxGenero;
    }

    public void setCmbxGenero(JComboBox<String> cmbxGenero) {
        this.cmbxGenero = cmbxGenero;
    }

    public JComboBox<String> getCmbxProvincia() {
        return cmbxProvincia;
    }

    public void setCmbxProvincia(JComboBox<String> cmbxProvincia) {
        this.cmbxProvincia = cmbxProvincia;
    }

    public JComboBox<String> getCmbxTipo() {
        return cmbxTipo;
    }

    public void setCmbxTipo(JComboBox<String> cmbxTipo) {
        this.cmbxTipo = cmbxTipo;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jtTodos = new javax.swing.JTabbedPane();
        listarFuncionarios = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaFuncionario = new javax.swing.JTable();
        pesquisaFun = new javax.swing.JTextField();
        btnPesquisar2 = new javax.swing.JButton();
        formFuncionario = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTelemovel1 = new javax.swing.JLabel();
        lblTelemovel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTelefone2 = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone1 = new javax.swing.JTextField();
        txtNif = new javax.swing.JTextField();
        txtBI = new javax.swing.JTextField();
        lblNif = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        lblProvincia = new javax.swing.JLabel();
        lblMunicipio = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        cmbxProvincia = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEndereco = new javax.swing.JTextArea();
        txtMunicipio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblIndica = new javax.swing.JLabel();
        lblNumBI = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        cmbxTipo = new javax.swing.JComboBox<>();
        txtSenha = new javax.swing.JPasswordField();
        lblSenha = new javax.swing.JLabel();
        cmbxGenero = new javax.swing.JComboBox<>();
        lblTipo = new javax.swing.JLabel();
        cmbxPais = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("SIG-Sistema de Gestão");
        setMaximumSize(new java.awt.Dimension(1367, 684));
        setPreferredSize(new java.awt.Dimension(1367, 684));
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(774, 51));

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIG-Funcionário");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sig/icones/delete.png"))); // NOI18N
        btnEliminar.setText("Eliminar");

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sig/icones/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sig/icones/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnImprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sig/icones/print.png"))); // NOI18N
        btnImprimir.setText("Imprimir");

        btnNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sig/icones/new.png"))); // NOI18N
        btnNovo.setText("Novo");

        jtTodos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtTodos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtTodos.setPreferredSize(new java.awt.Dimension(1341, 536));

        listarFuncionarios.setBackground(java.awt.Color.lightGray);
        listarFuncionarios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tabelaFuncionario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tabelaFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "NIF", "E-mail", "Telefone 1", "Telefone 2", "Provícia", "Endereço", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaFuncionario.setColumnSelectionAllowed(true);
        jScrollPane4.setViewportView(tabelaFuncionario);

        pesquisaFun.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pesquisaFun.setFocusCycleRoot(true);

        btnPesquisar2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisar2.setText("Pesquisar");

        javax.swing.GroupLayout listarFuncionariosLayout = new javax.swing.GroupLayout(listarFuncionarios);
        listarFuncionarios.setLayout(listarFuncionariosLayout);
        listarFuncionariosLayout.setHorizontalGroup(
            listarFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(listarFuncionariosLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(pesquisaFun, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(423, Short.MAX_VALUE))
        );
        listarFuncionariosLayout.setVerticalGroup(
            listarFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listarFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listarFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPesquisar2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(pesquisaFun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
        );

        jtTodos.addTab("Todos", listarFuncionarios);

        formFuncionario.setBackground(java.awt.Color.lightGray);
        formFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        formFuncionario.setMaximumSize(new java.awt.Dimension(2147483647, 16));

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNome.setText("Nome *");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEmail.setText("E-mail *");

        lblTelemovel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTelemovel1.setText("Telemóvel 1 *");

        lblTelemovel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTelemovel2.setText("Telemóvel 2");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTelefone2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTelefone1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNif.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtBI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblNif.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNif.setText("NIF *");

        lblPais.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPais.setText("País *");

        lblProvincia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblProvincia.setText("Província *");

        lblMunicipio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMunicipio.setText("Município *");

        lblEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEndereco.setText("Endereço *");

        cmbxProvincia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbxProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bengo", "Benguela", "Bié", "Cabinda", "Cuando-Cubango", "Cunene", "Huambo", "Huíla", "Kwanza Norte", "Kwanza Sul", "Luanda", "Lunda Norte", "Lunda Sul", "Malanje", "Moxico", "Namibe", "Uíge", "Zaire" }));

        txtEndereco.setColumns(20);
        txtEndereco.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtEndereco.setRows(5);
        jScrollPane1.setViewportView(txtEndereco);

        txtMunicipio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*");

        lblIndica.setText("Indica campo obrigatório");

        lblNumBI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNumBI.setText("BI nº *");

        lblGenero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblGenero.setText("Genéro *");

        cmbxTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gestor", "Normal" }));
        cmbxTipo.setToolTipText("");

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSenha.setText("Senha *");

        cmbxGenero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        cmbxGenero.setToolTipText("");

        lblTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTipo.setText("Tipo *");

        cmbxPais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbxPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Angola" }));
        cmbxPais.setToolTipText("");

        javax.swing.GroupLayout formFuncionarioLayout = new javax.swing.GroupLayout(formFuncionario);
        formFuncionario.setLayout(formFuncionarioLayout);
        formFuncionarioLayout.setHorizontalGroup(
            formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formFuncionarioLayout.createSequentialGroup()
                .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formFuncionarioLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(formFuncionarioLayout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(lblEmail))
                                .addGroup(formFuncionarioLayout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(lblNome)))
                            .addComponent(lblTelemovel1)
                            .addComponent(lblTelemovel2)
                            .addComponent(lblNif)
                            .addComponent(lblNumBI)
                            .addComponent(lblSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(txtBI)
                            .addComponent(txtNif)
                            .addComponent(txtTelefone2)
                            .addComponent(txtEmail)
                            .addComponent(txtTelefone1)
                            .addComponent(txtNome))
                        .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formFuncionarioLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblProvincia)
                                    .addComponent(lblMunicipio)
                                    .addComponent(lblPais)
                                    .addComponent(lblGenero))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(formFuncionarioLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEndereco)
                                    .addComponent(lblTipo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                                    .addComponent(cmbxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(formFuncionarioLayout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIndica)))
                .addContainerGap(448, Short.MAX_VALUE))
        );
        formFuncionarioLayout.setVerticalGroup(
            formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formFuncionarioLayout.createSequentialGroup()
                .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formFuncionarioLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGenero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPais))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProvincia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMunicipio))
                        .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formFuncionarioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblEndereco))
                            .addGroup(formFuncionarioLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(formFuncionarioLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome))
                        .addGap(12, 12, 12)
                        .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelemovel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelemovel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNif, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNif))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBI, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumBI))))
                .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formFuncionarioLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSenha)))
                    .addGroup(formFuncionarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(formFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblIndica))
                .addGap(19, 19, 19))
        );

        jtTodos.addTab("Cadastrar", formFuncionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1351, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addGap(23, 23, 23)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImprimir)
                        .addGap(0, 503, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEliminar)
                    .addComponent(btnImprimir)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        FuncionariosView fw = new FuncionariosView();
//         FuncionarioController fc = new FuncionarioController();
        fw.setTxtNome(txtNome);
        fw.setTxtEmail(txtEmail);
        fw.setTxtNif(txtNif);
        fw.setCmbxTipo(cmbxTipo);
        fw.setTxtSenha(txtSenha);
        fw.setTxtTelefone1(txtTelefone1);
        fw.setTxtTelefone2(txtTelefone2);
        fw.setCmbxGenero(cmbxGenero);
        fw.setCmbxPais(cmbxPais);
        fw.setCmbxProvincia(cmbxProvincia);
        fw.setTxtEndereco(txtEndereco);
        fw.setTxtSenha(txtSenha);
        fw.setCmbxTipo(cmbxTipo);
        fw.setTxtMunicipio(txtMunicipio);
        
        try {
            JOptionPane.showMessageDialog(null, fc.create(fw));
        } catch (Exception ex) {
            Logger.getLogger(FuncionariosView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar2;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbxGenero;
    private javax.swing.JComboBox<String> cmbxPais;
    private javax.swing.JComboBox<String> cmbxProvincia;
    private javax.swing.JComboBox<String> cmbxTipo;
    private javax.swing.JPanel formFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jtTodos;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblIndica;
    private javax.swing.JLabel lblMunicipio;
    private javax.swing.JLabel lblNif;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumBI;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelemovel1;
    private javax.swing.JLabel lblTelemovel2;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel listarFuncionarios;
    private javax.swing.JTextField pesquisaFun;
    private javax.swing.JTable tabelaFuncionario;
    private javax.swing.JTextField txtBI;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextArea txtEndereco;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNif;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTelefone1;
    private javax.swing.JTextField txtTelefone2;
    // End of variables declaration//GEN-END:variables
}
